sudo: false
language: python
python:
  - "2.7" 
before_install:
  - wget 'http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh' -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
install:
  - conda create --yes -n reform-test python=$TRAVIS_PYTHON_VERSION pip atlas numpy scipy
  - source activate reform-test
  - pip install -r requirements.txt
script:
  - coverage run --module unittest discover
after_success:
  - coverage combine
  - coverage report
  - coveralls

