name: reformulate
dependencies:
- openssl=1.0.2g=0
- pip=8.1.1=py27_0
- python=2.7.11=0
- readline=6.2=2
- setuptools=20.3=py27_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=0
- pip:
  - alabaster==0.7.7
  - babel==2.2.0
  - boto==2.39.0
  - bz2file==0.98
  - commonmark==0.5.4
  - coverage==4.0.3
  - coveralls==1.1
  - docutils==0.12
  - flake8==2.5.4
  - gensim==0.12.3
  - httpretty==0.8.10
  - jinja2==2.8
  - markupsafe==0.23
  - mccabe==0.4.0
  - nltk==3.1
  - numpy==1.10.1
  - pep8==1.7.0
  - ply==3.4
  - plyj==0.1
  - pyflakes==1.0.0
  - pygments==2.1.1
  - pytz==2015.7
  - recommonmark==0.4.0
  - requests==2.8.1
  - scipy==0.16.1
  - six==1.10.0
  - slimit==0.8.1
  - smart-open==1.3.2
  - snowballstemmer==1.2.1
  - sphinx==1.3.5
  - sphinx-rtd-theme==0.1.9
  - stemming==1.0.1

